### ISSUE TITLE
Feature: action that limits amount of open pull requests by the same author

### ISSUE THREAD

**Issue by SMillerDev** [Homebrew/actions#337]
As shortly discussed at the AGM, it would be good to have a limit on the amount of pull requests someone can have open in a repository at one time to ensure that one contributor does not overwhelm maintainer availability.

Suggestion: max 10 PRs per user per repository, with an optional override with a label for maintainers. The goal should after all be to merge PRs more than to just have them open.

**Comment by dawidd6** [comment]
Should the PRs opened over limit be closed by BrewTestBot with a comment explaining why or something else?

**Comment by SMillerDev** [comment]
I'm not sure about that, maybe we can start by just commenting. Either way it should be obvious to the author that they should open less PRs.

**Comment by MikeMcQuaid** [comment]
I gently disagree with this. This is a human problem that should be solved with human means i.e. asking the person to do so and blocking their ability to create more PRs if they do not comply.

**Comment by SMillerDev** [comment]
It seems the case is people who got very excited after their first merged PR and now decided to update all software they can find. We don't want to stop them from contributing, but asking them to pace themselves seems like a good idea.

> I'd consider instead of a warning: it's a hard error instead with no workaround.

I'd say it should be the same as an audit failure. Blocking, but you can force it to continue.

**Comment by MikeMcQuaid** [comment]
@SMillerDev Ok, that seems fair for now at least.

**Comment by AshwaqAzan** [comment]
Would be nice to have it

**Comment by iMichka** [comment]
Hi wrote a bunch of code to treat a similar problem here to showcase what is possible: https://github.com/Homebrew/homebrew-core/pull/162592

We could do the same for multiple PR's being opened (which is still an issue). (I initially thought @SMillerDev issue was from 2024, but I see we already discussed this issue in 2023).

There seem to be a disagreement on the strategy:
- Strategy 1: A human (maintainer) should talk to the users opening too many pull requests
- Strategy 2: A bot / code should do it instead of a human
- Strategy 2a: it needs to happen in bump-formula
- Strategy 2b: it needs to happen as a comment on Github / the PR should get closed automatically

I am in favour of using a bot; it removes the burden from the maintainers and contributors can't really argue with bots. I think that adding a comment on GitHub like I did in https://github.com/Homebrew/homebrew-core/pull/162592 is also more pedagogic so I would favour 2b.

**Comment by MikeMcQuaid** [comment]
Thanks for spelling out the options @iMichka!

> * Strategy 2a: it needs to happen in bump-formula

This is the next part I think we should work on. I'm game to do so but would actively encourage others to try to beat me to it.

> * Strategy 1: A human (maintainer) should talk to the users opening too many pull requests

This has been tried and doesn't seem to work 😭 

> * Strategy 2: A bot / code should do it instead of a human
> * Strategy 2b: it needs to happen as a comment on Github / the PR should get closed automatically

If 2a doesn't work: I think doing this as well would make sense.

**Comment by p-linnane** [comment]
>contributors can't really argue with bots

![image](https://github.com/Homebrew/actions/assets/105994585/b2bd142b-59c6-4155-844a-48459c39a237)

**Comment by p-linnane** [comment]
Agreed that the `bump` command should fail at the limit and explain why.

**Comment by MikeMcQuaid** [comment]
> f we can print a message explaining why we are asking users to slow down I think it would go a long way.

This is a very good idea 👍🏻

**Comment by SMillerDev** [comment]
I think that's a good idea, with the addition of referencing the file for the bot and the link being a general "help wanted" filter.

**Comment by ZhongRuoyu** [comment]
I have created a new `limit-pull-requests` action in #498. It can post comments on a PR and close it (although we probably don't want to) when the author already has a certain number of PRs open. A list of users and/or users with certain author associations (e.g. `MEMBER`) can be exempted, so @BrewTestBot can continue to do its job.
